@host = http://localhost:5000

### Register as Speaker
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "speaker@example.com",
  "password": "SecurePassword123!",
  "role": 0
}

### Register as Organizer
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "organizer@example.com",
  "password": "SecurePassword123!",
  "role": 1
}

### Register as Attendee
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "attendee@example.com",
  "password": "SecurePassword123!",
  "role": 2
}

### Login as Speaker
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "speaker@example.com",
  "password": "SecurePassword123!"
}

### Login as Organizer
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "organizer@example.com",
  "password": "SecurePassword123!"
}
